"""Mermaid diagram builder for graph visualization."""

import re
from typing import List, Dict, Optional
from .graph_model import GraphModel, ComponentNode, IntentEdge, ComponentType, RiskLevel, EdgeType


class MermaidBuilder:
    """Builds Mermaid flowchart code from graph model."""
    
    def __init__(self, graph_model: GraphModel):
        self.graph = graph_model
        self.node_ids: Dict[str, str] = {}
        self._generate_node_ids()
    
    def _generate_node_ids(self) -> None:
        """Generate simplified IDs for Mermaid."""
        for idx, node_id in enumerate(self.graph.nodes.keys()):
            self.node_ids[node_id] = f"N{idx}"
    
    def _clean_string(self, text: str) -> str:
        """Clean string for Mermaid compatibility."""
        if not text:
            return "unknown"
        # Remove special characters and keep only alphanumeric and underscores
        clean = re.sub(r'[^a-zA-Z0-9_]', '_', text)
        # Replace multiple underscores with single
        clean = re.sub(r'_+', '_', clean)
        # Remove leading/trailing underscores
        clean = clean.strip('_')
        return clean if clean else "component"
    
    def _get_node_shape(self, node: ComponentNode, display_name: str) -> str:
        """Get Mermaid node shape based on component type."""
        shapes = {
            ComponentType.ACTIVITY: f"[{display_name}]",
            ComponentType.SERVICE: f"{{{display_name}}}",
            ComponentType.BROADCAST_RECEIVER: f"({display_name})",
            ComponentType.CONTENT_PROVIDER: f"[{display_name}]"
        }
        return shapes.get(node.type, f"[{display_name}]")
    
    def build(self) -> str:
        """Build complete Mermaid flowchart code."""
        lines = ["flowchart TB"]
        
        # Add title
        lines.append("%% Attack Surface Graph")
        lines.append("%% Generated by Attack Surface Mapper")
        lines.append("")
        
        # Create subgraphs for better organization
        exported_nodes = []
        internal_nodes = []
        
        for node_id, node in self.graph.nodes.items():
            if node.exported:
                exported_nodes.append(node_id)
            else:
                internal_nodes.append(node_id)
        
        # Internal components subgraph
        if internal_nodes:
            lines.append("    subgraph InternalComponents [Internal Components]")
            lines.append("        direction TB")
            for node_id in internal_nodes:
                node = self.graph.nodes[node_id]
                mermaid_id = self.node_ids[node_id]
                clean_name = self._clean_string(node.name)
                shape = self._get_node_shape(node, clean_name)
                lines.append(f"        {mermaid_id}{shape}")
            lines.append("    end")
            lines.append("")
        
        # Exported components subgraph
        if exported_nodes:
            lines.append("    subgraph ExportedComponents [Exported Components]")
            lines.append("        direction TB")
            for node_id in exported_nodes:
                node = self.graph.nodes[node_id]
                mermaid_id = self.node_ids[node_id]
                clean_name = self._clean_string(node.name)
                shape = self._get_node_shape(node, clean_name)
                lines.append(f"        {mermaid_id}{shape}")
            lines.append("    end")
            lines.append("")
        
        # Add edges
        for edge in self.graph.edges:
            source_id = self.node_ids[edge.source_id]
            target_id = self.node_ids[edge.target_id]
            
            # Different line styles for edge types
            style_map = {
                EdgeType.INTENT: "-->",
                EdgeType.PERMISSION: "-.->",
                EdgeType.DATA_FLOW: "-..->",
                EdgeType.EXPORT: "==>"
            }
            
            style = style_map.get(edge.type, "-->")
            
            if edge.label:
                clean_label = self._clean_string(edge.label)
                lines.append(f"    {source_id} {style}|{clean_label}| {target_id}")
            else:
                lines.append(f"    {source_id} {style} {target_id}")
        
        # Add styling classes
        lines.append("")
        lines.append("%% Risk-based styling")
        
        risk_configs = {
            "critical": "fill:#dc3545,stroke:#721c24,stroke-width:2px,color:#ffffff",
            "high": "fill:#fd7e14,stroke:#856404,stroke-width:2px,color:#ffffff",
            "medium": "fill:#ffc107,stroke:#856404,stroke-width:1px,color:#333333",
            "low": "fill:#28a745,stroke:#155724,stroke-width:1px,color:#ffffff",
            "info": "fill:#17a2b8,stroke:#0c5460,stroke-width:1px,color:#ffffff"
        }
        
        for risk, config in risk_configs.items():
            lines.append(f"    classDef {risk} {config};")
        
        # Apply classes to nodes
        risk_classes = {"critical": [], "high": [], "medium": [], "low": [], "info": []}
        for node_id, node in self.graph.nodes.items():
            mermaid_id = self.node_ids[node_id]
            risk = node.risk_level.value
            if risk in risk_classes:
                risk_classes[risk].append(mermaid_id)
        
        for risk, node_list in risk_classes.items():
            if node_list:
                lines.append(f"    class {','.join(node_list)} {risk};")
        
        return "\n".join(lines)